# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oH8SwVGuBm3m4LXy2QNJ0XuD_uBICX1M
"""

import requests

# ==========================
# GROQ API CONFIGURATION
# ==========================
API_KEY = "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"
API_URL = "https://api.groq.com/openai/v1/chat/completions"
MODEL = "llama-3.1-8b-instant"

# ==========================
# FUNCTION TO GET RESPONSE
# ==========================
def travel_chatbot(user_query, history):
    system_prompt = """
You are a friendly and knowledgeable Travel Guide Chatbot.

Your responsibilities:
- Recommend tourist attractions.
- Suggest hotels and restaurants.
- Provide travel itineraries.
- Share local food recommendations.
- Give travel safety tips.
- Explain local culture and customs.
- Suggest transportation options.
- Estimate travel budgets.
- Answer only travel-related questions politely.
"""

    messages = [{"role": "system", "content": system_prompt}]
    messages.extend(history)
    messages.append({"role": "user", "content": user_query})

    payload = {
        "model": MODEL,
        "messages": messages,
        "temperature": 0.5,
        "max_tokens": 500
    }

    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }

    response = requests.post(API_URL, headers=headers, json=payload)

    if response.status_code == 200:
        return response.json()["choices"][0]["message"]["content"]
    else:
        return f"Error {response.status_code}: {response.text}"

# ==========================
# MAIN PROGRAM
# ==========================
def main():
    print("=" * 50)
    print("🌍 Welcome to the AI Travel Guide Chatbot!")
    print("Type 'exit' to quit.")
    print("=" * 50)

    history = []

    while True:
        user_input = input("\nYou: ")

        if user_input.lower() == "exit":
            print("Travel Bot: Have a wonderful trip! Safe travels! ✈️")
            break

        reply = travel_chatbot(user_input, history)

        print("\nTravel Bot:", reply)

        history.append({"role": "user", "content": user_input})
        history.append({"role": "assistant", "content": reply})

if __name__ == "__main__":
    main()